trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'my-acr-connection'
  imageRepository: 'flask-demo'
  containerRegistry: 'myflaskacr.azurecr.io'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageRepository)'
    dockerfile: '**/Dockerfile'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: |
      $(tag)
      latest

- task: PublishBuildArtifacts@1
  displayName: 'Publish Kubernetes Manifests'
  inputs:
    pathToPublish: 'deployment.yaml'
    artifactName: 'manifests'