apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: myflaskacr.azurecr.io/flask-demo:latest  # Replace with your ACR name
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-demo-service
spec:
  selector:
    app: flask-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer